version: "3.9"

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:

services:

  opensearch-01:
    image: opensearchproject/opensearch:1.0.1
    environment:
    - node.name=opensearch-01
    - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
    - opensearch-data1:/usr/share/opensearch/data
    - ./admin.crt:/usr/share/opensearch/config/admin.crt:ro
    - ./admin.pem:/usr/share/opensearch/config/admin.pem:ro
    - ./ca.crt:/usr/share/opensearch/config/ca.crt:ro
    - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
  
  opensearch-02:
    image: opensearchproject/opensearch:1.0.1
    environment:
    - node.name=opensearch-02
    - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
    - opensearch-data2:/usr/share/opensearch/data
    - ./admin.crt:/usr/share/opensearch/config/admin.crt:ro
    - ./admin.pem:/usr/share/opensearch/config/admin.pem:ro
    - ./ca.crt:/usr/share/opensearch/config/ca.crt:ro
    - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro

  opensearch-03:
    image: opensearchproject/opensearch:1.0.1
    environment:
    - node.name=opensearch-03
    - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
    - opensearch-data3:/usr/share/opensearch/data
    - ./admin.crt:/usr/share/opensearch/config/admin.crt:ro
    - ./admin.pem:/usr/share/opensearch/config/admin.pem:ro
    - ./ca.crt:/usr/share/opensearch/config/ca.crt:ro
    - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:1.0.1
    ports:
    - 5601:5601
    environment:
    - opensearch.hosts=["https://opensearch-01:9200","https://opensearch-02:9200","https://opensearch-02:9200"]
