version: "3.9"

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:

services:

  opensearch-01:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    environment:
    - node.name=opensearch-01
    - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
    - opensearch-data1:/usr/share/elasticsearch/data
    - ./admin.crt:/usr/share/elasticsearch/config/admin.crt:ro
    - ./admin.pem:/usr/share/elasticsearch/config/admin.pem:ro
    - ./ca.crt:/usr/share/elasticsearch/config/ca.crt:ro
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  
  opensearch-02:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    environment:
    - node.name=opensearch-02
    - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
    - opensearch-data2:/usr/share/elasticsearch/data
    - ./admin.crt:/usr/share/elasticsearch/config/admin.crt:ro
    - ./admin.pem:/usr/share/elasticsearch/config/admin.pem:ro
    - ./ca.crt:/usr/share/elasticsearch/config/ca.crt:ro
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  opensearch-03:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    environment:
    - node.name=opensearch-03
    - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
    - opensearch-data3:/usr/share/elasticsearch/data
    - ./admin.crt:/usr/share/elasticsearch/config/admin.crt:ro
    - ./admin.pem:/usr/share/elasticsearch/config/admin.pem:ro
    - ./ca.crt:/usr/share/elasticsearch/config/ca.crt:ro
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  opensearch-dashboard:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    ports:
    - 5601:5601
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    - ./ca.crt:/usr/share/kibana/config/cacert.crt:ro